name: Test push after commit

on: 
  push:
    branches:
      - main
    paths:
      - 'test/**'     # run on specific folder(s) only

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test 
    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - name: Get changed JSON files in a given folder
        id: changed-json-files
        uses: tj-actions/changed-files@v39
        with:
          files: test/*.json
      - name: List all changed files
        run: echo '${{ steps.changed-json-files.outputs.all_changed_and_modified_files }}'
      - name: push-to-postman-action
        id: push-to-postman
        uses: gcatanese/push-to-postman-action@main
        with:
          goal: create
          postman-key: ${{ secrets.POSTMAN_API_KEY }}
          postman-file: ${{ steps.changed-json-files.outputs.all_changed_and_modified_files }}
          workspace-id: ${{ secrets.POSTMAN_WORKSPACE_ID }}
