name: "From OpenAPI file to Postman"

on:
  workflow_dispatch:
    inputs:
      file:
        description: 'OpenAPI filepath'     
        required: true
        default: 'test/openapi/test.yml'
jobs:
  generate:
    name: "Generate Postman Collection"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: addnab/docker-run-action@v3
        with:
          image: openapitools/openapi-generator-cli
          options: -v ${{ github.workspace }}:/local
          run: |
            echo "Generate postman.json from ${{ github.event.inputs.file }}"
            /usr/local/bin/docker-entrypoint.sh generate -i /local/${{ github.event.inputs.file }} -g postman-collection -o /local/out
      - name: push-to-postman-action
        id: push-to-postman
        uses: gcatanese/push-to-postman-action@main
        with:
          goal: createOrUpdate
          postman-key: ${{ secrets.POSTMAN_API_KEY }}
          postman-file: /local/out/postman.json
          workspace-id: ${{ secrets.POSTMAN_WORKSPACE_ID }}
