name: "From OpenAPI file to Postman"

on:
  workflow_dispatch:
    inputs:
      file:
        description: 'OpenAPI filepath'     
        required: true
        default: 'test/openapi/test.yml'
jobs:
  generate:
    name: "Generate Postman Collection"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: addnab/docker-run-action@v3
        with:
          image: openapitools/openapi-generator-cli
          options: -v ${{ github.workspace }}:/local
          run: |
            echo "Start"
            /usr/local/bin/docker-entrypoint.sh generate -i /local/${{ github.event.inputs.file }} -g postman-collection -o /local/out
